# Generated by Django 4.2.5 on 2023-09-23 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 7, 0, 4, 192520, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 7, 0, 4, 192177, tzinfo=datetime.timezone.utc)),
        ),
    ]
